### ISSUE TITLE
403 error after opening filemanager popup

### ISSUE THREAD

**Issue by OlegBodyansky** [stepanenko3/nova-filemanager#1]
Request URL: https://local.loc/nova-vendor/stepanenko3/nova-filemanager/pages/picture/data?folder=filemanager
Request Method: GET
Status Code: 403 Forbidden

it reproduces with a flexible form, a usual form, when a folder exists and no

**Comment by stepanenko3** [comment]
Thanks, @OlegBodyansky ,

I'll watch it in the coming days

**Comment by OlegBodyansky** [comment]
Forget to add tool
