### ISSUE TITLE
Error: Target class [Stepanenko3\\NovaFilemanager\\Http\\Controllers\\Stepanenko3\\NovaFilemanager\\Http\\Controllers\\FilemanagerToolController] does not exist.

### ISSUE THREAD

**Issue by RoliJ** [stepanenko3/nova-filemanager#2]
Hi! Thanks for your efforts for upgrading the nova filemanager.

I installed this packages as follows:

- `composer require stepanenko3/nova-filemanager`
- `php artisan vendor:publish --provider="Stepanenko3\NovaFilemanager\ToolServiceProvider"`

And to use it, in `NovaServiceProvider` I added this:
```
public function tools()
    {
        return [
            new \Stepanenko3\NovaFilemanager\FilemanagerTool(),
        ];
    }
```
Am I missing something? Because I get the following error:
`Target class [Stepanenko3\\NovaFilemanager\\Http\\Controllers\\Stepanenko3\\NovaFilemanager\\Http\\Controllers\\FilemanagerToolController] does not exist.`

Appreciate your help!
R.

**Comment by stepanenko3** [comment]
Thanks, @RoliJ ,

I'll watch it in the coming days

**Comment by RoliJ** [comment]
@stepanenko3 , appreciate it.

**Comment by RoliJ** [comment]
@stepanenko3 , with Nova 4, Laravel 9, PHP 8 and Vue3, I did not see the error anymore. But, the upload button doesn't work. I will  close this, and will open a new issue on this.

Thanks

**Comment by andrii-trush** [comment]
Hello @stepanenko3 Is it possible to fix for Laravel 8?
