### ISSUE TITLE
The upload button doesn't work

### ISSUE THREAD

**Issue by RoliJ** [stepanenko3/nova-filemanager#3]
@stepanenko3, using Nova 4, Laravel 9, PHP 8 and Vue3, the upload button doesn't work (no errors, no actions).

Thanks

**Comment by stepanenko3** [comment]
@RoliJ, Thank you for issue
The download is still under development

**Comment by RoliJ** [comment]
@stepanenko3, thanks for the resond. And, thanks for your efforts.

**Comment by stepanenko3** [comment]
@RoliJ, I'm working on it at PR #5
