### ISSUE TITLE
guide on how to implement?

### ISSUE THREAD

**Issue by rickdroce** [stepanenko3/nova-filemanager#6]
Hello, is there any sort of guide/steps on how to implement this? 
In the read.me i only see the composer install command and some screenshot, but it seems that your report doesn't work with the same "filemanager.php" config file used for the other repository (which doesn't support nova 4)

**Comment by stepanenko3** [comment]
Hi, @rickdroce 

I'll do it a little later

**Comment by Lezhni** [comment]
@rickdroce you can copy config file directly from `vendor` folder

**Comment by mikaelpopowicz** [comment]
Given that version 5 is a stale copy of [https://github.com/oneduo/nova-file-manager](https://github.com/oneduo/nova-file-manager), check out [our documentation](https://oneduo.github.io/nova-file-manager).
