### ISSUE TITLE
Filtering images

### ISSUE THREAD

**Issue by OlegBodyansky** [stepanenko3/nova-filemanager#8]
I'd like to describe the issue on the next line.
 #[Filters](https://github.com/stepanenko3/nova-filemanager/blob/master/src/Services/GetFiles.php#L85)

public function filterData($files, $filter)
 this method takes the filter to files ok its good
 But  this returns an array of the filters rules
`  $filters = config('filemanager.filters', []);`
What does method check inside an array if the $filter is true or false?
[issue](https://github.com/stepanenko3/nova-filemanager/blob/master/src/Services/GetFiles.php#L89)

I always get $filtered  as undefined
```
file: "/nova-filemanager/src/Http/Services/GetFiles.php"
message: "Undefined variable $filtered"
```

**Comment by stepanenko3** [comment]
Fixed in https://github.com/stepanenko3/nova-filemanager/releases/tag/v5.0.2
